# intervals
:root: [0, 0]
:min_2: [1, 1]
:maj_2: [2, 1]
:sharp_9: [3, 1]
:min_3: [3, 2]
:maj_3: [4, 2]
:p_4: [5, 3]
:a_4: [6, 3]
:d_5: [6, 4]
:p_5: [7, 4]
:a_5: [8, 4]
:min_6: [8, 5]
:maj_6: [9, 5]
:d_7: [9, 6]
:min_7: [10, 6]
:maj_7: [11, 6]